name: Build Wails App

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    name: Build for Windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install MinGW-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Add Go bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Install NSIS
        run: sudo apt-get install -y nsis

      - name: Install frontend dependencies
        if: ${{ hashFiles('frontend/package.json') != '' }}
        run: |
          cd frontend
          npm ci

      - name: Build Wails app for Windows
        run: |
          export PATH="${HOME}/go/bin:${PATH}"
          GOOS=windows GOARCH=amd64 wails build

      - name: Build NSIS installer
        run: |
          makensis /DARG_WAILS_AMD64_BINARY=build/bin/hammerdin.exe build/windows/installer/project.nsi

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: wails-windows-build
          path: build/bin/*.exe

      - name: Upload NSIS installer
        uses: actions/upload-artifact@v4
        with:
          name: nsis-installer
          path: build/windows/installer/*.exe